#!/usr/bin/env node
/**
 * Generates TypeScript modules from the plain-data JSON in protocol/schema/
 * (see beam_protocol.export_data). This data -- the wordlist and the SAS symbol
 * table -- can't be expressed as JSON Schema like the message types codegen-protocol.mjs
 * handles, but it's still shared, generated data: nothing here is meant to be
 * hand-edited on the TypeScript side (docs/architecture.md §2).
 *
 * Usage: node scripts/codegen-data.mjs
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SCHEMA_DIR = path.resolve(__dirname, "../../protocol/schema");
const OUT_DIR = path.resolve(__dirname, "../src/engine/generated");

const BANNER = `/**
 * AUTO-GENERATED by scripts/codegen-data.mjs from protocol/schema/*.json.
 * Do not edit by hand -- change the Python source in protocol/src/beam_protocol/
 * and re-run \`npm run codegen\` instead. See docs/architecture.md §2.
 */
`;

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const wordlist = JSON.parse(await readFile(path.join(SCHEMA_DIR, "wordlist.json"), "utf-8"));
  await writeFile(
    path.join(OUT_DIR, "wordlist.ts"),
    BANNER + `\nexport const WORDLIST: readonly string[] = ${JSON.stringify(wordlist)};\n`,
  );

  const sasTable = JSON.parse(await readFile(path.join(SCHEMA_DIR, "sas-table.json"), "utf-8"));
  const entries = sasTable.map((e) => [e.emoji, e.name]);
  await writeFile(
    path.join(OUT_DIR, "sas-table.ts"),
    BANNER +
      `\nexport const SAS_TABLE: readonly (readonly [string, string])[] = ${JSON.stringify(entries)};\n`,
  );

  console.log(`Generated 2 data file(s) into ${OUT_DIR}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
